### ISSUE TITLE
Add utility method for labeling roles.

### ISSUE THREAD

**Issue by cristianberneanu** [diffix/pg_diffix#327]
Since we have methods for labeling tables, we should also provide a method for labeling users.

**Comment by edongashi** [comment]
The hardest part about this is finding a suitable name for the procedure... Any ideas?

**Comment by cristianberneanu** [comment]
`mark_trusted` and `mark_untrusted` would keep consistency.
Or `mark_role` which accepts `trusted/untrusted` as arguments.

**Comment by cristianberneanu** [comment]
In the same vein, we also need a way to unlabel objects.
Something like `diffix.unmark` which accepts either a role or table as argument.

**Comment by edongashi** [comment]
> In the same vein, we also need a way to unlabel objects. Something like `diffix.unmark` which accepts either a role or table as argument.

Sounds good if we can get rid of the low level seclabel management.

FYI: `pg_seclabel` stores table/column labels, whereas `pg_shseclabel` stores labels for roles. The latter is a global catalog across all databases.
