### ISSUE TITLE
Add unlabel versions for relation, aid col, role

### ISSUE THREAD

**Issue by edongashi** [diffix/pg_diffix#333]
Continuation of #327. I think these should be separate functions to avoid potential ambiguities.
Something like `unmark_table`, `unmark_column`, `unmark_role`.

**Comment by cristianberneanu** [comment]
Providing an `unmark_column` method doesn't seem useful, since table marking takes care of resetting the column labels.
Also, there isn't a corresponding `mark_column` method.

**Comment by edongashi** [comment]
Yes, you're right. Let's keep table/columns marking/unmarking atomic.
