### ISSUE TITLE
Accept groupref quals (HAVING-like) in WHERE

### ISSUE THREAD

**Issue by edongashi** [diffix/pg_diffix#349]
Consider the following query which post processes the output buckets:

```sql
SELECT city, age, count(*)
FROM customers
GROUP BY 1, 2
HAVING city LIKE 'B%' OR age > 10;
```

If we dump the final (anonymizing) plan, we see the following leaf seq scan node (rest of plan is omitted):

```
:lefttree {SEQSCAN
  :startup_cost 0.00
  :total_cost 6.09
  :plan_rows 204
  :plan_width 14
  :parallel_aware false
  :parallel_safe false
  :plan_node_id 1
  :targetlist (
    {TARGETENTRY ...}
    {TARGETENTRY ...}
    {TARGETENTRY ...}
    {TARGETENTRY ...}
    {TARGETENTRY ...}
    {TARGETENTRY ...}
  )
  :qual (
    {BOOLEXPR
      :boolop or
      :args (
        {OPEXPR
          :opno 1209
          :opfuncid 850
          :opresulttype 16
          :opretset false
          :opcollid 0
          :inputcollid 100
          :args (
            {VAR
              :varno 1
              :varattno 5
              :vartype 25
              :vartypmod -1
              :varcollid 100
              :varlevelsup 0
              :varnosyn 1
              :varattnosyn 5
              :location 63
            }
            {CONST
              :consttype 25
              :consttypmod -1
              :constcollid 100
              :constlen -1
              :constbyval false
              :constisnull false
              :location 73
              :constvalue 6 [ 24 0 0 0 66 37 ]
            }
          )
          :location 68
        }
        {OPEXPR
          :opno 521
          :opfuncid 147
          :opresulttype 16
          :opretset false
          :opcollid 0
          :inputcollid 0
          :args (
            {VAR
              :varno 1
              :varattno 4
              :vartype 23
              :vartypmod -1
              :varcollid 0
              :varlevelsup 0
              :varnosyn 1
              :varattnosyn 4
              :location 81
            }
            {CONST
              :consttype 23
              :consttypmod -1
              :constcollid 0
              :constlen 4
              :constbyval true
              :constisnull false
              :location 87
              :constvalue 4 [ 10 0 0 0 0 0 0 0 ]
            }
          )
          :location 85
        }
      )
      :location -1
    }
  )
  :lefttree <>
  :righttree <>
  :initPlan <>
  :extParam (b)
  :allParam (b)
  :scanrelid 1
}
```

We can notice that Postgres has moved the `qual` down to the `SeqScan` instead of `Agg`.
That is because it detected that filtering does not affect final groups and can be done sooner.

The above query is therefore identical to:

```sql
SELECT city, age, count(*)
FROM customers
WHERE city LIKE 'B%' OR age > 10;
GROUP BY 1, 2
```

Which we reject. `pg_diffix` should accept `HAVING`-like quals (for lack of a better word) in `WHERE` clauses without any restrictions or additional noise.
I think to ensure whether is something safe we need to inspect the where tree and check if **all** expressions are valid grouprefs in the current query.

If done like described above, it's more a quality of life improvement rather than a feature, considering users can simply write `HAVING`, which may not be very intuitive to some.

**Comment by pdobacz** [comment]
The utility of this might be reduced by how hard it would be to explain which `WHERE`s are supported and which aren't. It's easier to say "You cannot use WHERE, try HAVING instead".

Other concern is - are these truly equivalent? Wouldn't LED for example have different semantics, if it would be deprived of the rows not satisfying the condition? I'm not sure about this one, so pardon if I make no sense here.

**Comment by edongashi** [comment]
> Wouldn't LED for example have different semantics, if it would be deprived of the rows not satisfying the condition?

Crap, considering Postgres pushes the filter down in either case, we already get different LED and star bucket semantics...

The star bucket can be affected by putting a negative condition in `WHERE`. For example we can add `HAVING city <> 'London'`. If the star bucket output changes it means that there is a suppressed `London` bucket...

**Comment by edongashi** [comment]
Suspending until we fix the `qual` issue.
