### ISSUE TITLE
Preloading the extension globally prevents access to databases for which it wasn't activated.

### ISSUE THREAD

**Issue by cristianberneanu** [diffix/pg_diffix#357]
When the extension is preloaded using the system configuration file, which applies to all sessions, regardless of the target database, the extension code executes even for those databases with which it wasn't associated.

We should detect associated databases somehow and disable anonymization for non-associated ones.
One approach would be to detect if the `diffix` schema exists during load. Another would be to mark the database with a security label during setup. Not sure now which is best.

**Comment by edongashi** [comment]
I think I have seen extensions do some checks during loading. If only I can remember where I saw it...
