### ISSUE TITLE
Allow accessing `information_schema...` tables

### ISSUE THREAD

**Issue by pdobacz** [diffix/pg_diffix#377]
As reported by Paul:

```
SELECT table_name
FROM information_schema.tables
WHERE table_schema='public'
AND table_catalog='banking' 
```

And I get this error:

```
[PG_DIFFIX] Tables without an anonymization label can't be accessed in anonymized mode.
```

For some reason it works with `pg_catalog....` tables.

One workaround is to use `treat_unmarked_tables_as_public = on;` setting

**Comment by edongashi** [comment]
Also `pg_catalog.pg_tables` is not whitelisted.
